#!/bin/sh

export LFS=/mnt/lfs

mkdir -p $LFS/sources/build_dir

mount -v --bind /dev              $LFS/dev
mount -v --bind /dev/pts          $LFS/dev/pts
mount -vt       proc proc         $LFS/proc
mount -vt       sysfs sysfs       $LFS/sys
mount -vt       tmpfs tmpfs       $LFS/run
mount -vt       tmpfs tmpfs       $LFS/sources/build_dir
mount -vt       efivarfs efivarfs $LFS/sys/firmware/efi/efivars/

chroot "$LFS" /usr/bin/env -i          \
    HOME=/root                         \
    TERM="$TERM"                       \
    PS1='(lfs chroot) \u:\w\$ '        \
    PATH=/bin:/usr/bin:/sbin:/usr/sbin \
    /bin/bash --login +h
