#!/bin/sh

save_lib="ld-2.33.so libc-2.33.so libpthread-2.33.so libthread_db-1.0.so
          libquadmath.so.0.0.0 libstdc++.so.6.0.28
          libitm.so.1.0.0 libatomic.so.1.2.0"

pushd /usr/lib
for LIB in $save_usrlib; do
    objcopy --only-keep-debug $LIB $LIB.dbg
    strip --strip-unneeded $LIB
    objcopy --add-gnu-debuglink=$LIB.dbg $LIB
done
popd

unset LIB save_lib

find /usr/lib -type f -name \*.a \
   -exec strip --strip-debug {} ';'

find /usr/lib -type f -name \*.so\* ! -name \*dbg \
   -exec strip --strip-unneeded {} ';'

find /usr/{bin,sbin,libexec} -type f \
    -exec strip --strip-all {} ';'

find /usr/lib /usr/libexec -name \*.la -delete
