#!/bin/sh

mkdir -p /var/snapshots
mount -t tmpfs tmpfs /var/snapshots

btrfs subvolume snapshot -r / /var/snapshots/lfs-snapshot
mount /dev/backupVolGroup/lfs_backups /mnt/backups

pushd /mnt/backups

cat > excludes.txt << EOF
./boot/*
./mnt/*
./sources/*
./usr/src/*
./proc/*
./sys/*
./dev/*
./run/*
./tmp/*
EOF

tar --exclude-from=excludes.txt                               \
    --acls                                                    \
    --xattrs                                                  \
    -cpJf                                                     \
    lfs-backup-$(date --iso-8601=minutes | tr -d ':-').tar.xz \
    -C /var/snapshots/lfs-snapshot .

popd

btrfs subvolume delete /var/snapshots/lfs-snapshot

umount /var/snapshots